### PR TITLE
add support for gradient of a constant

### PR DESCRIPTION
**Pull request by arnavs**
Errors otherwise, when it should return a vector of `0`s.

### CODE REVIEW

**Comment by arnavs** [comment]
Travis is failing due to an upstream reason (can't install `ForwardDiff` on 1.1, 1.0, so none of the tests are running for those versions.)

**Comment by wupeifan** [comment]
Out of curiosity (and please ignore if it is not important), what are the error messages without this patch? The `expand_derivatives` function is applying chain rule dirrectly, and it should return 0 when it is a constant.

**Comment by arnavs** [comment]
@wupeifan See below. It'll just fail without the patch. Because `Constant` isn't an operation, and the dispatch only works for `Operation`s.

```
julia> ModelingToolkit.gradient(x, [b])
ERROR: MethodError: no method matching gradient(::ModelingToolkit.Constant, ::Array{Operation,1})
```

**Comment by wupeifan** [comment]
> Because Constant isn't an operation,

I see, thanks! The alternative is wrapping a `Constant` as `Operation`. Either way... You guys decide :)

**Comment by arnavs** [comment]
@YingboMa I think this is ready to go (see the Travis build for confirmation.)

**Comment by wupeifan** [comment]
Sure, it's not the bottleneck -- the bottleneck is still higher-order derivatives.

**Comment by arnavs** [comment]
@YingboMa Any news on `ForwardDiff2`?

**Comment by YingboMa** [comment]
Closed by ForwardDiff2.jl

**Comment by wupeifan** [comment]
Actually there's a similar issue. Let me give an MWE here.

**Comment by wupeifan** [comment]
``` Julia
using ModelingToolkit
using ForwardDiff2: DI
using ChainRules

@scalar_rule(^(x, y), (y * x^(y - 1), Ω * log(x)))

function equations(vars, theta, n_exo, n_endo)
    # ForwardDiff Dual<:Real
    # X: (k, z)
    # Y: (c)
    XP = vars[1:n_exo]
    X = vars[(n_exo + 1):(2 * n_exo)]
    YP = vars[(2 * n_exo + 1):(2 * n_exo + n_endo)]
    Y = vars[(2 * n_exo + n_endo + 1):(2 * (n_exo + n_endo))]
    beta, alpha, delta, rho, sigma = theta
    equ = [ 1 / Y[1] - beta / YP[1] * (alpha * exp(XP[2]) * XP[1] ^ (alpha - 1) + 1 - delta),
            Y[1] + XP[1] - (1 - delta) * X[1] - exp(X[2]) * X[1] ^ alpha,
            XP[2] - rho * X[2]]
    return equ
end

@variables beta, alpha, delta, rho, sigma
@variables k, z, c, k_p, z_p, c_p

vars_sym = [k_p, z_p, k, z, c_p, c]
theta_sym = [beta, alpha, delta, rho, sigma]

# this one fails
julia> d2HdθdX = DI(vars_arg -> DI(theta_arg -> equations(vars_arg, theta_arg, 2, 1))(theta_sym))(vars_sym)
ERROR: MethodError: no method matching AbstractFloat(::ModelingToolkit.Constant)
Closest candidates are:
  AbstractFloat(::T) where T<:Number at boot.jl:718
  AbstractFloat(::Bool) at float.jl:258
  AbstractFloat(::Int8) at float.jl:259

# but the following works
julia> d2HdθdX = DI(theta_arg -> DI(vars_arg -> equations(vars_arg, theta_arg, 2, 1))(vars_sym))(theta_sym)
18×5 Array{Operation,2}: (omitted)
```

**Comment by arnavs** [comment]
@YingboMa: @wupeifan is saying this should be re-opened.

**Comment by YingboMa** [comment]
Oh this PR is actually wrong

**Comment by YingboMa** [comment]
https://github.com/JuliaDiffEq/ModelingToolkit.jl/pull/240

**Pull request closed without merging**
