### PR TITLE
Start on API documentation

### PR DESCRIPTION
**Pull request by jlumpe**
Added basic docstrings to most of the core types and a few functions. Created documentation skeleton with API page showing docstrings.

### CODE REVIEW

**Comment by jlumpe** [comment]
@HarrisonGrodin makes sense, I've removed the documentation for all fields which seem to have accessors. Those were `ODESystem` and `NonlinearSystem` (except for `.exprs`), and `Constant.value` (which is available through `Base.get()`).

**Comment by jlumpe** [comment]
@HarrisonGrodin the [most recent build](https://travis-ci.org/JuliaDiffEq/ModelingToolkit.jl/builds/525139452) passed but it didn't seem to update here. This should be ready to merge.

**Comment by HarrisonGrodin** [comment]
It seems like there are still some TODOs?

**Comment by jlumpe** [comment]
I actually intentionally left those in for other developers who know more about how the package works than I do. I can remove them if you don't want them in master.

**Comment by jlumpe** [comment]
@HarrisonGrodin merge conflicts resolved, should I remove the TODOs or leave them in?
\

**Comment by ChrisRackauckas** [comment]
The hold up is really that we don't know what the public API really should be yet... but screw it. Let's merge and keep refining it.

**Pull request merged**
